# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: atlassian/default-image:latest

# enable Docker for your repository
options:
  docker: true

pipelines:
  default:
    - parallel:
      - step:
          name: build php 5
          script:
            - export IMAGE_NAME=tundraray/php-nginx
            - docker build -t ${IMAGE_NAME}:5 --rm=true -f php5.Dockerfile . --pull=true
      - step:
          name: build php 7
          script:
            - export IMAGE_NAME=tundraray/php-nginx
            - docker build -t ${IMAGE_NAME}:7 -t ${IMAGE_NAME}:latest --rm=true -f php7.Dockerfile . --pull=true
            #- docker build -t tundraray/php-nginx:7 -t tundraray/php-nginx:latest --rm=true -f php7.Dockerfile . --pull=true
    - step:
        name: Push to docker
        services:
          - docker
        caches:
          - docker
        script:
          - export IMAGE_NAME=tundraray/php-nginx
          - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
          - docker push $IMAGE_NAME